package types

import "time"

type Pull struct {
	Type string `json:"type"`
	Pull struct {
		URL                 string `json:"url"`
		ID                  int    `json:"id"`
		NodeID              string `json:"node_id"`
		HTMLURL             string `json:"html_url"`
		DiffURL             string `json:"diff_url"`
		PatchURL            string `json:"patch_url"`
		IssueURL            string `json:"issue_url"`
		CommitsURL          string `json:"commits_url"`
		ReviewCommentsURL   string `json:"review_comments_url"`
		ReviewCommentURL    string `json:"review_comment_url"`
		CommentsURL         string `json:"comments_url"`
		StatusesURL         string `json:"statuses_url"`
		Number              int    `json:"number"`
		State               string `json:"state"`
		Locked              bool   `json:"locked"`
		MaintainerCanModify bool   `json:"maintainer_can_modify"`
		Title               string `json:"title"`
		User                struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		Body   string `json:"body"`
		Labels []struct {
			ID      int    `json:"id"`
			NodeID  string `json:"node_id"`
			URL     string `json:"url"`
			Name    string `json:"name"`
			Color   string `json:"color"`
			Default bool   `json:"default"`
		} `json:"labels"`
		CreatedAt          time.Time `json:"created_at"`
		UpdatedAt          time.Time `json:"updated_at"`
		ClosedAt           time.Time `json:"closed_at"`
		MergeableState     string    `json:"mergeable_state"`
		MergedAt           time.Time `json:"merged_at"`
		MergeCommitSha     string    `json:"merge_commit_sha"`
		Assignees          []any     `json:"assignees"`
		RequestedReviewers []any     `json:"requested_reviewers"`
		RequestedTeams     []any     `json:"requested_teams"`
		Head               struct {
			Label string `json:"label"`
			Ref   string `json:"ref"`
			Sha   string `json:"sha"`
			User  struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"user"`
			Repo struct {
				ID       int    `json:"id"`
				NodeID   string `json:"node_id"`
				Name     string `json:"name"`
				FullName string `json:"full_name"`
				Owner    struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"owner"`
				Private          bool      `json:"private"`
				HTMLURL          string    `json:"html_url"`
				Description      string    `json:"description"`
				Fork             bool      `json:"fork"`
				URL              string    `json:"url"`
				ArchiveURL       string    `json:"archive_url"`
				AssigneesURL     string    `json:"assignees_url"`
				BlobsURL         string    `json:"blobs_url"`
				BranchesURL      string    `json:"branches_url"`
				CollaboratorsURL string    `json:"collaborators_url"`
				CommentsURL      string    `json:"comments_url"`
				CommitsURL       string    `json:"commits_url"`
				CompareURL       string    `json:"compare_url"`
				ContentsURL      string    `json:"contents_url"`
				ContributorsURL  string    `json:"contributors_url"`
				DeploymentsURL   string    `json:"deployments_url"`
				DownloadsURL     string    `json:"downloads_url"`
				EventsURL        string    `json:"events_url"`
				ForksURL         string    `json:"forks_url"`
				GitCommitsURL    string    `json:"git_commits_url"`
				GitRefsURL       string    `json:"git_refs_url"`
				GitTagsURL       string    `json:"git_tags_url"`
				GitURL           string    `json:"git_url"`
				IssueCommentURL  string    `json:"issue_comment_url"`
				IssueEventsURL   string    `json:"issue_events_url"`
				IssuesURL        string    `json:"issues_url"`
				KeysURL          string    `json:"keys_url"`
				LabelsURL        string    `json:"labels_url"`
				LanguagesURL     string    `json:"languages_url"`
				MergesURL        string    `json:"merges_url"`
				MilestonesURL    string    `json:"milestones_url"`
				NotificationsURL string    `json:"notifications_url"`
				PullsURL         string    `json:"pulls_url"`
				ReleasesURL      string    `json:"releases_url"`
				SSHURL           string    `json:"ssh_url"`
				StargazersURL    string    `json:"stargazers_url"`
				StatusesURL      string    `json:"statuses_url"`
				SubscribersURL   string    `json:"subscribers_url"`
				SubscriptionURL  string    `json:"subscription_url"`
				TagsURL          string    `json:"tags_url"`
				TeamsURL         string    `json:"teams_url"`
				TreesURL         string    `json:"trees_url"`
				CloneURL         string    `json:"clone_url"`
				HooksURL         string    `json:"hooks_url"`
				SvnURL           string    `json:"svn_url"`
				Homepage         string    `json:"homepage"`
				Language         string    `json:"language"`
				ForksCount       int       `json:"forks_count"`
				StargazersCount  int       `json:"stargazers_count"`
				WatchersCount    int       `json:"watchers_count"`
				Size             int       `json:"size"`
				DefaultBranch    string    `json:"default_branch"`
				OpenIssuesCount  int       `json:"open_issues_count"`
				IsTemplate       bool      `json:"is_template"`
				Topics           []any     `json:"topics"`
				HasIssues        bool      `json:"has_issues"`
				HasProjects      bool      `json:"has_projects"`
				HasWiki          bool      `json:"has_wiki"`
				HasPages         bool      `json:"has_pages"`
				HasDownloads     bool      `json:"has_downloads"`
				Archived         bool      `json:"archived"`
				Disabled         bool      `json:"disabled"`
				Visibility       string    `json:"visibility"`
				PushedAt         time.Time `json:"pushed_at"`
				CreatedAt        time.Time `json:"created_at"`
				UpdatedAt        time.Time `json:"updated_at"`
				License          struct {
					Key            string `json:"key"`
					Name           string `json:"name"`
					NodeID         string `json:"node_id"`
					SpdxID         string `json:"spdx_id"`
					URL            string `json:"url"`
					HTMLURL        any    `json:"html_url"`
					Description    any    `json:"description"`
					Implementation any    `json:"implementation"`
					Permissions    any    `json:"permissions"`
					Conditions     any    `json:"conditions"`
					Limitations    any    `json:"limitations"`
					Body           any    `json:"body"`
					Featured       any    `json:"featured"`
				} `json:"license"`
			} `json:"repo"`
		} `json:"head"`
		Base struct {
			Label string `json:"label"`
			Ref   string `json:"ref"`
			Sha   string `json:"sha"`
			User  struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"user"`
			Repo struct {
				ID       int    `json:"id"`
				NodeID   string `json:"node_id"`
				Name     string `json:"name"`
				FullName string `json:"full_name"`
				Owner    struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"owner"`
				Private          bool      `json:"private"`
				HTMLURL          string    `json:"html_url"`
				Description      string    `json:"description"`
				Fork             bool      `json:"fork"`
				URL              string    `json:"url"`
				ArchiveURL       string    `json:"archive_url"`
				AssigneesURL     string    `json:"assignees_url"`
				BlobsURL         string    `json:"blobs_url"`
				BranchesURL      string    `json:"branches_url"`
				CollaboratorsURL string    `json:"collaborators_url"`
				CommentsURL      string    `json:"comments_url"`
				CommitsURL       string    `json:"commits_url"`
				CompareURL       string    `json:"compare_url"`
				ContentsURL      string    `json:"contents_url"`
				ContributorsURL  string    `json:"contributors_url"`
				DeploymentsURL   string    `json:"deployments_url"`
				DownloadsURL     string    `json:"downloads_url"`
				EventsURL        string    `json:"events_url"`
				ForksURL         string    `json:"forks_url"`
				GitCommitsURL    string    `json:"git_commits_url"`
				GitRefsURL       string    `json:"git_refs_url"`
				GitTagsURL       string    `json:"git_tags_url"`
				GitURL           string    `json:"git_url"`
				IssueCommentURL  string    `json:"issue_comment_url"`
				IssueEventsURL   string    `json:"issue_events_url"`
				IssuesURL        string    `json:"issues_url"`
				KeysURL          string    `json:"keys_url"`
				LabelsURL        string    `json:"labels_url"`
				LanguagesURL     string    `json:"languages_url"`
				MergesURL        string    `json:"merges_url"`
				MilestonesURL    string    `json:"milestones_url"`
				NotificationsURL string    `json:"notifications_url"`
				PullsURL         string    `json:"pulls_url"`
				ReleasesURL      string    `json:"releases_url"`
				SSHURL           string    `json:"ssh_url"`
				StargazersURL    string    `json:"stargazers_url"`
				StatusesURL      string    `json:"statuses_url"`
				SubscribersURL   string    `json:"subscribers_url"`
				SubscriptionURL  string    `json:"subscription_url"`
				TagsURL          string    `json:"tags_url"`
				TeamsURL         string    `json:"teams_url"`
				TreesURL         string    `json:"trees_url"`
				CloneURL         string    `json:"clone_url"`
				HooksURL         string    `json:"hooks_url"`
				SvnURL           string    `json:"svn_url"`
				Homepage         string    `json:"homepage"`
				Language         string    `json:"language"`
				ForksCount       int       `json:"forks_count"`
				StargazersCount  int       `json:"stargazers_count"`
				WatchersCount    int       `json:"watchers_count"`
				Size             int       `json:"size"`
				DefaultBranch    string    `json:"default_branch"`
				OpenIssuesCount  int       `json:"open_issues_count"`
				IsTemplate       bool      `json:"is_template"`
				Topics           []string  `json:"topics"`
				HasIssues        bool      `json:"has_issues"`
				HasProjects      bool      `json:"has_projects"`
				HasWiki          bool      `json:"has_wiki"`
				HasPages         bool      `json:"has_pages"`
				HasDownloads     bool      `json:"has_downloads"`
				Archived         bool      `json:"archived"`
				Disabled         bool      `json:"disabled"`
				Visibility       string    `json:"visibility"`
				PushedAt         time.Time `json:"pushed_at"`
				CreatedAt        time.Time `json:"created_at"`
				UpdatedAt        time.Time `json:"updated_at"`
				License          struct {
					Key            string `json:"key"`
					Name           string `json:"name"`
					NodeID         string `json:"node_id"`
					SpdxID         string `json:"spdx_id"`
					URL            string `json:"url"`
					HTMLURL        any    `json:"html_url"`
					Description    any    `json:"description"`
					Implementation any    `json:"implementation"`
					Permissions    any    `json:"permissions"`
					Conditions     any    `json:"conditions"`
					Limitations    any    `json:"limitations"`
					Body           any    `json:"body"`
					Featured       any    `json:"featured"`
				} `json:"license"`
			} `json:"repo"`
		} `json:"base"`
		Links struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
		} `json:"_links"`
		AuthorAssociation string `json:"author_association"`
		Draft             bool   `json:"draft"`
		Additions         int    `json:"additions"`
		Deletions         int    `json:"deletions"`
		ChangedFiles      int    `json:"changed_files"`
		Commits           int    `json:"commits"`
		ReviewComments    int    `json:"review_comments"`
		Comments          int    `json:"comments"`
	} `json:"pull"`
	Events []struct {
		Event     string `json:"event"`
		ID        any    `json:"id"`
		NodeID    string `json:"node_id"`
		URL       string `json:"url"`
		Actor     any    `json:"actor"`
		CommitID  any    `json:"commit_id"`
		CommitURL any    `json:"commit_url"`
		CreatedAt any    `json:"created_at"`
		HTMLURL   string `json:"html_url,omitempty"`
		Tree      struct {
			Sha string `json:"sha"`
			URL string `json:"url"`
		} `json:"tree,omitempty"`
		Verification struct {
			Verified  bool   `json:"verified"`
			Reason    string `json:"reason"`
			Payload   any    `json:"payload"`
			Signature any    `json:"signature"`
		} `json:"verification,omitempty"`
		Parents []struct {
			URL     string `json:"url"`
			Sha     string `json:"sha"`
			HTMLURL string `json:"html_url"`
		} `json:"parents,omitempty"`
		Message   string `json:"message,omitempty"`
		Committer struct {
			Name  string    `json:"name"`
			Email string    `json:"email"`
			Date  time.Time `json:"date"`
		} `json:"committer,omitempty"`
		Author struct {
			Name  string    `json:"name"`
			Email string    `json:"email"`
			Date  time.Time `json:"date"`
		} `json:"author,omitempty"`
		Sha       string    `json:"sha,omitempty"`
		UpdatedAt time.Time `json:"updated_at,omitempty"`
		Source    struct {
			Issue struct {
				ID            int    `json:"id"`
				NodeID        string `json:"node_id"`
				URL           string `json:"url"`
				RepositoryURL string `json:"repository_url"`
				LabelsURL     string `json:"labels_url"`
				CommentsURL   string `json:"comments_url"`
				EventsURL     string `json:"events_url"`
				HTMLURL       string `json:"html_url"`
				Number        int    `json:"number"`
				State         string `json:"state"`
				StateReason   string `json:"state_reason"`
				Title         string `json:"title"`
				Body          string `json:"body"`
				User          struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"user"`
				Labels            []any     `json:"labels"`
				Assignees         []any     `json:"assignees"`
				AuthorAssociation string    `json:"author_association"`
				Locked            bool      `json:"locked"`
				ActiveLockReason  string    `json:"active_lock_reason"`
				Comments          int       `json:"comments"`
				ClosedAt          time.Time `json:"closed_at"`
				CreatedAt         time.Time `json:"created_at"`
				UpdatedAt         time.Time `json:"updated_at"`
			} `json:"issue"`
			Type string `json:"type"`
		} `json:"source,omitempty"`
	} `json:"events"`
	Comments []any `json:"comments"`
}
