name: Build Sonar Worker
on:
  push:
    branches: [ "master" , "dev" ]
    paths:
      - 'workers/sonar-worker/**'
  workflow_dispatch:

jobs:
  build_sonar:
    name: sonar-worker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup env variables
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
          echo "SONAR_IMAGE=public.ecr.aws/i3s2n0b6/corecheck-sonar-worker-dev:latest" >> $GITHUB_ENV
        else
          echo "SONAR_IMAGE=public.ecr.aws/i3s2n0b6/corecheck-sonar-worker-default:latest" >> $GITHUB_ENV
        fi
    - name: Configure AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-1
    - name: Login to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i3s2n0b6
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: workers/sonar-worker
        push: true
        platforms: linux/amd64
        tags: ${{ env.SONAR_IMAGE }}
